version: "3"
services:
  web:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - /etc/nginx/:/etc/nginx/
      - /etc/nginx/conf.d/:/etc/nginx/conf.d
  spring1:
    build: .
    ports:
      - 8081:8081
    volumes:
      - ./:/root/
    environment:
      active: real1
  spring2:
    build: .
    ports:
      - 8082:8082
    volumes:
      - ./:/root/
    environment:
      active: real2